import { Poppins, Jost } from "next/font/google";

import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

// const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400','500','600','700','800'],
  variable: "--primary-font"
})
const jost = Jost({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400','500','600','700','800'],
  variable: "--secondary-font"
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${jost.variable}`} data-bs-theme="light">
        <Header/>
        {children}
         <Footer/>
      </body>
    </html>
  );
}
